export const COPY = {
  help: "Ayuda",
  signIn: "Iniciar sesión",
  signOut: "Cerrar sesión",
  email: "Correo electrónico",
  password: "Contraseña",
  phoneNumber: "Número de teléfono",
  "add.to.cart": "Añadir al carrito",
  "auth.username": "Usuario",
  "auth.name": "Nombre completo",
  "auth.name.error.required": "El nombre completo es un campo requerido.",
  "auth.name.error.notValid": "Ingrese un nombre completo valido.",
  "auth.rut": "Rut",
  "auth.email": "Correo electrónico",
  "auth.email.error.required": "El correo electrónico es un campo requerido.",
  "auth.email.error.notValid": "Ingrese un correo electrónico valido.",
  "auth.password": "Contraseña",
  "auth.passwordConfirmation": "Confirmación de contraseña",
  "auth.password.error.required": "La contraseña es un campo requerido.",
  "auth.password.error.minLength":
    "La contraseña debe contener 6 caracteres como mínimo.",
  "auth.passwordConfirmation.error.required":
    "La confirmación de contraseña es un campo requerido.",
  "auth.passwordConfirmation.error.passwordsDoNotMatch":
    "Las contraseñas no coinciden. Intente nuevamente.",
  "auth.login": "Entrar",
  "auth.logIn": "Iniciar Sesion",
  "auth.signup": "Registrarme",
  "profile.change-password": "Cambiar contraseña",
  "new-password": "Nueva contraseña",
  "update-your-password":"Actualiza tu contraseña",
  "auth.reset": "Recuperar Contraseña",
  "edit":"Editar",
  "update": "Actualizar",
  "password-update-success": "Contraseña actualizada correctamente",
  "featured.products":"Productos Destacados",
  "errors.order-cancelled-or-denied":"Tu orden fue cancelada o rechaza por flow, intenta nuevamente",
  "errors.cant-connect-to-gateway": "No se pudo establecer conexión con la pasarela de pago, intente mas tarde",
  "errors.invalid-products-in-cart": "Algunos productos de tu carrito son invalidos",
  "errors.invalid-cart-amount": "El monto total a pagar no supera el minimo de pago (350$) o es invalido",
  "pay":"Pagar",
  "total":"Total",
  "profile.imageProfile": "Imagen de perfil",
  "profile.name": "Nombre",
  "profile.lastName": "Apellido",
  "profile.email": "Correo",
  "profile.phone": "Teléfono",
  "profile.address": "Direccion",
  "profile.latitude": "Latitud",
  "profile.data": "Datos de perfil",
  "profile.faq": "Preguntas frecuentes",
  "profile.longitude": "Longitude",
  "profile.kiphu": "Kiphu",
  "profile.history": "Historial",
  "profile.payments": "Pagos",
  "profile.orders": "Pedidos",
  "profile.mutate.success": "Perfil actualizado con exito",
  "profile.create.success": "Perfil creado con exito",
  "profile.btn1": "Actualizar",
  "profile.btn2": "Registrar",
  "product.btn": "Agregar",
  "menu.home": "Inicio",
  "menu.product": "Productos",
  "menu.history": "Historial",
  "menu.profile": "Perfil",
  "menu.orders": "Pedidos",
  "menu.category": "Categorias",
  "menu.cart": "Carrito",
  "menu.contacts": "Contactos",
  "error.default": "Error no identificado por favor intente mas tarde",
  "errors.nocameraorgallery": "Lo sentimos, necesitamos la disponer de tu camara y/o galeria para poder editar tu foto de perfil",
  "menu.contacts.create": "Agregar contacto",
  "menu.contacts.detail": "Detalles de contacto",
  "menu.contacts.update": "Editar contacto",
  "menu.contacts.delete": "Eliminar contacto",
  "menu.contacts.delete.description": (name) =>
    `¿Está seguro de que desea eliminar el contacto ${name}?`,
  "menu.contacts.delete.error": (name) =>
    `Hubo un error al tratar de eliminar ${name}`,
  "menu.webhooks": "Webhooks",
  "menu.accounts": "Cuentas",
  "menu.support": "Soporte y Ayuda",
  "menu.terms": "Términos y condiciones",
  "menu.about": "Sobre Condominio Angostura",
  "menu.lab": "🚧   WIP LAB   🚧",
  "menu.logout": "Cerrar sesión",
  "menu.settings": "Configuración",
  "menu.settings.security": "Seguridad",
  "menu.settings.notifications": "Notificaciones",
  "menu.settings.accounts": "Cuentas",
  "menu.transactions": "Transacciones",
  "menu.transfer": "Transferir",
  "menu.advertisements": "Anuncios",
  "menu.loading": "Cargando...",
  "menu.expand.sidebar.expand": "Expandir",
  "menu.expand.sidebar.minimize": "Minimizar",
  "order.received":"Orden Recibida",
  "order.received.suggest":"Revisa el estado de tus ordenes:",
  "shipping-address": "Informacion de envio",
  "home.welcomeTitle": (userFirstName) => `Buen día, ${userFirstName} 👋🏻`,
  "orders": "Pedidos",
  darkMode: "Modo oscuro",
  settings: "Configuración",
  logOut: "Cerrar sesión",
  back: "Volver",
  error: "Ha ocurrido un error",
  add: "Agregar",
  saveChanges: "Guardar cambios",
  "alert.cancel": "Cancelar",
  "alert.ok": "OK",
  "return.home":"volver al inicio",
  "loader.title": "Cargando",
  "profile": "Perfil"
};
